version: "3.9"
name: defensa_civil_moreno
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - monguito
  #   volumes:
  #     - .:/home/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=def-civil-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mochila123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # postgres -> /data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  postgres-data: 